//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWebParking.Model
{
    using System;
    using System.ComponentModel.DataAnnotations;

    public partial class spgetAvailableparkingsTypeCount
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Desription { get; set; }
        [DisplayFormat(DataFormatString = "{0:C0}")]
        public decimal Price { get; set; }
        [Display(Name ="Remaining Positions")]
        public Nullable<int> remainingPositions { get; set; }
    }
}
